import { NextResponse } from "next/server";
import { z } from "zod";
import { isContractTransactionConflict, runContractTransaction } from "@/lib/contract-exclusivity";
import { reconcileExpiredContracts } from "@/lib/contract-lifecycle";
import { createTextId } from "@/lib/ids";
import { synchronizePropertyContractState } from "@/lib/property-contract-state";
import { getActiveSession } from "@/lib/server-auth";
import { hasValidContractDateRange, isWithinRenewalWindow } from "@/lib/temporal-state-validation";
const renewalSchema=z.object({proposedEndDate:z.string().datetime().optional()}).strict();
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}) { const session=await getActiveSession(); if(!session||session.role!=="ARRENDATARIO")return NextResponse.json({error:"Solo el arrendatario puede solicitar renovacion"},{status:403}); const parsed=renewalSchema.safeParse(await request.json().catch(()=>({})));if(!parsed.success)return NextResponse.json({error:"Fecha de renovacion invalida"},{status:400});const id=(await params).id;try{const result=await runContractTransaction(async(client)=>{const now=new Date();await reconcileExpiredContracts(client,now);const r=await client.query<{id:string;propertyId:string;tenantId:string;endDate:Date;startDate:Date;status:string}>('SELECT id,"propertyId","tenantId","startDate","endDate",status FROM public.contracts WHERE id=$1 FOR UPDATE',[id]);const contract=r.rows[0];if(!contract||contract.tenantId!==session.sub)return{error:"Contrato no disponible para renovacion",status:404};if(contract.status!=="ACTIVO")return{error:"El contrato no esta disponible para renovacion",status:409};if(!isWithinRenewalWindow(contract.endDate,now))return{error:"La renovacion se habilita durante los ultimos 15 dias de vigencia",status:409};const proposed=parsed.data.proposedEndDate?new Date(parsed.data.proposedEndDate):new Date(new Date(contract.endDate).setFullYear(contract.endDate.getFullYear()+1));if(!hasValidContractDateRange(contract.startDate,proposed)||proposed<=contract.endDate)return{error:"La nueva fecha final debe extender el contrato vigente",status:400};const existing=await client.query('SELECT 1 FROM public.contract_renewal_requests WHERE "contractId"=$1 AND status=\'PENDIENTE\'::"RequestStatus"',[id]);if(existing.rowCount)return{error:"Ya existe una solicitud de renovacion pendiente",status:409};const marked=await client.query('UPDATE public.contracts SET status=\'EN_RENOVACION\'::"ContractStatus","updatedAt"=$2 WHERE id=$1 AND status=\'ACTIVO\'::"ContractStatus"',[id,now]);if(marked.rowCount!==1)return{error:"El contrato cambio durante la solicitud",status:409};const renewal=await client.query('INSERT INTO public.contract_renewal_requests (id,"contractId","requestedBy","proposedEndDate","updatedAt") VALUES ($1,$2,$3,$4,$5) RETURNING *',[createTextId(),id,session.sub,proposed,now]);await synchronizePropertyContractState(client,contract.propertyId,now);return{renewal:renewal.rows[0]};});return"error"in result?NextResponse.json({error:result.error},{status:result.status}):NextResponse.json(result,{status:201});}catch(error){if(isContractTransactionConflict(error))return NextResponse.json({error:"La solicitud de renovacion entro en conflicto; intentalo de nuevo"},{status:409});console.error("contract renewal request error",error);return NextResponse.json({error:"No se pudo solicitar la renovacion"},{status:500});}}
