"use client";

import { useEffect, useState, type FormEvent } from "react";
import { notifyNavigationBadgesChanged } from "@/components/layout/navigation-badges";
import { Alert, Button, EmptyState, StatusBadge } from "@/components/ui";

type Contract = { id: string; status: string; startDate: string; endDate: string; properties: { title: string; address: string } };
type Renewal = { id: string; status: "PENDIENTE" | "APROBADO" | "RECHAZADO"; proposedEndDate: string; createdAt: string; contract: Contract };
type Props = { role: "ARRENDADOR" | "ARRENDATARIO"; contracts: Contract[]; onChanged: () => Promise<void> };

function dateValue(date: string) { return new Date(date).toISOString().slice(0, 10); }
function isEligible(contract: Contract) { const remaining = (new Date(contract.endDate).getTime() - Date.now()) / 86_400_000; return contract.status === "ACTIVO" && remaining >= 0 && remaining <= 15; }

export function ContractRenewalPanel({ role, contracts, onChanged }: Props) {
  const [renewals, setRenewals] = useState<Renewal[]>([]); const [selected, setSelected] = useState<Contract | null>(null);
  const [proposedEndDate, setProposedEndDate] = useState(""); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = async () => { const response = await fetch("/api/contract-renewals", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "No se pudieron cargar las renovaciones"); setRenewals(data.renewals ?? []); };
  useEffect(() => { void load().catch((reason) => setError(reason instanceof Error ? reason.message : "No se pudieron cargar las renovaciones")); }, []);
  const requestRenewal = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected || !proposedEndDate) return; setBusy(selected.id); setError(null); try { const response = await fetch(`/api/contracts/${selected.id}/renewal`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ proposedEndDate: new Date(`${proposedEndDate}T00:00:00.000Z`).toISOString() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "No se pudo solicitar la renovación"); setSelected(null); setProposedEndDate(""); await Promise.all([load(), onChanged()]); notifyNavigationBadgesChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo solicitar la renovación"); } finally { setBusy(null); } };
  const decide = async (renewal: Renewal, decision: "APROBAR" | "RECHAZAR") => { setBusy(renewal.id); setError(null); try { const response = await fetch(`/api/contract-renewals/${renewal.id}/decision`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "No se pudo decidir la renovación"); await Promise.all([load(), onChanged()]); notifyNavigationBadgesChanged(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo decidir la renovación"); } finally { setBusy(null); } };
  const eligible = contracts.filter(isEligible);

  return <section className="app-panel p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-emerald-700">Continuidad contractual</p><h3 className="mt-2 text-xl font-black text-navy">Renovaciones</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">Las solicitudes se habilitan durante los últimos 15 días del contrato.</p></div><span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-success">{renewals.length} registradas</span></div>{error ? <Alert tone="danger" className="mt-5" title="No se pudo actualizar la renovación">{error}</Alert> : null}{role === "ARRENDATARIO" && eligible.length > 0 ? <div className="mt-5 flex flex-wrap gap-2">{eligible.map((contract) => <Button key={contract.id} variant="primary" disabled={busy !== null} onClick={() => { setSelected(contract); setProposedEndDate(""); }}>Renovar {contract.properties.title}</Button>)}</div> : null}{role === "ARRENDATARIO" && selected ? <form onSubmit={(event) => void requestRenewal(event)} className="mt-5 rounded-xl border border-sky/20 bg-sky/[.04] p-4"><p className="font-bold text-navy">Solicitud para {selected.properties.title}</p><label className="mt-3 block max-w-xs"><span className="text-sm font-bold text-navy">Nueva fecha final</span><input required type="date" min={dateValue(selected.endDate)} value={proposedEndDate} onChange={(event) => setProposedEndDate(event.target.value)} className="field-input mt-2 px-3 py-2" /></label><div className="mt-4 flex flex-wrap gap-2"><Button type="submit" loading={busy === selected.id}>Enviar solicitud</Button><Button type="button" variant="secondary" onClick={() => setSelected(null)}>Cancelar</Button></div></form> : null}<div className="mt-5 space-y-3">{renewals.length === 0 ? <EmptyState title="No hay renovaciones registradas" description="Cuando exista una solicitud de renovación, podrás consultarla aquí." /> : renewals.map((renewal) => <article key={renewal.id} className="rounded-xl border border-border bg-surface-subtle/40 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-black text-navy">{renewal.contract.properties.title}</p><p className="mt-1 text-sm text-muted-foreground">Actual: {new Date(renewal.contract.endDate).toLocaleDateString("es-EC")} · Propuesta: {new Date(renewal.proposedEndDate).toLocaleDateString("es-EC")}</p></div><StatusBadge status={renewal.status} /></div>{role === "ARRENDADOR" && renewal.status === "PENDIENTE" ? <div className="mt-4 flex flex-wrap gap-2"><Button loading={busy === renewal.id} onClick={() => void decide(renewal, "APROBAR")}>Aprobar</Button><Button loading={busy === renewal.id} variant="danger" onClick={() => void decide(renewal, "RECHAZAR")}>Rechazar</Button></div> : null}</article>)}</div></section>;
}
