"use client";

import dynamic from "next/dynamic";
import { ChangeEvent, DragEvent, FormEvent, useRef, useState } from "react";

const LocationPickerMap = dynamic(() => import("@/components/location-picker-map").then((module) => module.LocationPickerMap), { ssr: false, loading: () => <div className="mt-6 h-[360px] animate-pulse rounded-xl bg-slate-200" /> });

type FormValues = { title: string; address: string; price: string; bedrooms: string; bathrooms: string; description: string; latitude: string; longitude: string };
const initialValues: FormValues = { title: "", address: "", price: "", bedrooms: "", bathrooms: "", description: "", latitude: "", longitude: "" };
const serviceOptions = ["Agua", "Luz", "Internet"] as const;
const amenityOptions = ["Piscina", "Seguridad Privada", "Wi-Fi", "Parqueo"] as const;

export function PropertyPublishForm() {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [values, setValues] = useState(initialValues);
  const [services, setServices] = useState<Record<string, boolean>>({});
  const [amenities, setAmenities] = useState<Record<string, boolean>>({});
  const [photos, setPhotos] = useState<File[]>([]);
  const [dragging, setDragging] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState(false);
  const [locating, setLocating] = useState(false);

  function updateValue(field: keyof FormValues, value: string) { setValues((current) => ({ ...current, [field]: value })); setSuccess(false); setError(""); }
  function addPhotos(files: File[]) { setPhotos((current) => [...current, ...files.filter((file) => file.type.startsWith("image/"))].slice(0, 12)); setError(""); }
  function handleFileChange(event: ChangeEvent<HTMLInputElement>) { addPhotos(Array.from(event.target.files ?? [])); }
  function handleDrop(event: DragEvent<HTMLDivElement>) { event.preventDefault(); setDragging(false); addPhotos(Array.from(event.dataTransfer.files)); }
  function removePhoto(index: number) { setPhotos((current) => current.filter((_, photoIndex) => photoIndex !== index)); }
  function updateCoordinates(latitude: string, longitude: string) { setValues((current) => ({ ...current, latitude, longitude })); setError(""); setSuccess(false); }

  function useCurrentLocation() {
    if (!navigator.geolocation) { setError("Tu navegador no permite obtener la ubicación actual."); return; }
    setLocating(true); setError("");
    navigator.geolocation.getCurrentPosition(({ coords }) => { updateCoordinates(coords.latitude.toFixed(6), coords.longitude.toFixed(6)); setLocating(false); }, () => { setError("No fue posible obtener tu ubicación. Revisa los permisos del navegador."); setLocating(false); }, { enableHighAccuracy: true, timeout: 10000, maximumAge: 300000 });
  }

  function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); setSuccess(false);
    if (photos.length < 3) { setError("Debes agregar mínimo 3 fotos para publicar la propiedad."); return; }
    const payload = { ...values, price: Number(values.price), bedrooms: Number(values.bedrooms), bathrooms: Number(values.bathrooms), latitude: Number(values.latitude), longitude: Number(values.longitude), services: serviceOptions.filter((service) => services[service]), amenities: amenityOptions.filter((amenity) => amenities[amenity]), photos: photos.map((photo) => photo.name) };
    console.log("Propiedad lista para publicar:", payload); setSuccess(true);
  }

  return <form onSubmit={handleSubmit} className="space-y-7">
    <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-lg shadow-slate-200/60 sm:p-8"><div className="mb-6"><p className="text-sm font-bold uppercase tracking-[.16em] text-sky">Paso 1</p><h2 className="mt-2 text-2xl font-black text-navy">Datos generales</h2><p className="mt-2 text-sm text-slate-500">Estos datos aparecerán en el catálogo y en el detalle de tu propiedad.</p></div><div className="grid gap-5 md:grid-cols-2"><label className="space-y-2 md:col-span-2"><span className="text-sm font-bold text-navy">Título de la publicación</span><input required value={values.title} onChange={(event) => updateValue("title", event.target.value)} placeholder="Ej. Departamento con vista al mar" className="field-input" /></label><label className="space-y-2 md:col-span-2"><span className="text-sm font-bold text-navy">Dirección</span><input required value={values.address} onChange={(event) => updateValue("address", event.target.value)} placeholder="Ej. Tarqui, Barbasquillo o Av. Flavio Reyes" className="field-input" /></label><label className="space-y-2"><span className="text-sm font-bold text-navy">Precio mensual (USD)</span><div className="relative"><span className="pointer-events-none absolute left-4 top-3 text-slate-500">$</span><input required min="1" step="0.01" type="number" value={values.price} onChange={(event) => updateValue("price", event.target.value)} placeholder="450" className="field-input pl-8" /></div></label><label className="space-y-2"><span className="text-sm font-bold text-navy">Cuartos</span><input required min="1" type="number" value={values.bedrooms} onChange={(event) => updateValue("bedrooms", event.target.value)} placeholder="2" className="field-input" /></label><label className="space-y-2"><span className="text-sm font-bold text-navy">Baños</span><input required min="1" type="number" value={values.bathrooms} onChange={(event) => updateValue("bathrooms", event.target.value)} placeholder="2" className="field-input" /></label><label className="space-y-2 md:col-span-2"><span className="text-sm font-bold text-navy">Descripción de la propiedad</span><textarea required rows={4} value={values.description} onChange={(event) => updateValue("description", event.target.value)} placeholder="Describe la ciudadela, seguridad, acceso a piscina y otros detalles importantes..." className="field-input resize-y" /></label></div></section>
    <section className="grid gap-7 lg:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white p-6 shadow-lg shadow-slate-200/60 sm:p-8"><p className="text-sm font-bold uppercase tracking-[.16em] text-sky">Paso 2</p><h2 className="mt-2 text-2xl font-black text-navy">Servicios y comodidades</h2><p className="mt-2 text-sm text-slate-500">Selecciona lo que incluye el alquiler.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{[...serviceOptions, ...amenityOptions].map((option) => { const isService = (serviceOptions as readonly string[]).includes(option); return <label key={option} className="flex cursor-pointer items-center gap-3 rounded-lg border border-slate-200 p-3 font-semibold text-navy transition hover:border-sky has-[:checked]:border-blue has-[:checked]:bg-blue/5"><input type="checkbox" checked={isService ? services[option] ?? false : amenities[option] ?? false} onChange={(event) => isService ? setServices((current) => ({ ...current, [option]: event.target.checked })) : setAmenities((current) => ({ ...current, [option]: event.target.checked }))} className="h-4 w-4 accent-[#0055A5]" />{option}</label>; })}</div></div><div className="rounded-xl border border-slate-200 bg-white p-6 shadow-lg shadow-slate-200/60 sm:p-8"><p className="text-sm font-bold uppercase tracking-[.16em] text-violet">Paso 3</p><h2 className="mt-2 text-2xl font-black text-navy">Imágenes</h2><div onClick={() => fileInputRef.current?.click()} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={handleDrop} className={`mt-5 cursor-pointer rounded-xl border-2 border-dashed p-7 text-center transition ${dragging ? "border-violet bg-violet/10" : "border-violet/50 bg-violet/[.03] hover:bg-violet/10"}`}><input ref={fileInputRef} type="file" accept="image/*" multiple onChange={handleFileChange} className="hidden" /><div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-violet/10 text-2xl text-violet">↑</div><p className="mt-3 font-bold text-navy">Arrastra tus imágenes aquí o haz clic para buscar</p><p className="mt-1 text-xs text-slate-500">Mínimo 3 fotos requeridas · Hasta 12 imágenes</p></div>{photos.length > 0 ? <div className="mt-4 grid grid-cols-3 gap-2">{photos.map((photo, index) => <div key={`${photo.name}-${index}`} className="group relative overflow-hidden rounded-lg bg-slate-100"><img src={URL.createObjectURL(photo)} alt={photo.name} className="h-20 w-full object-cover" /><button type="button" onClick={(event) => { event.stopPropagation(); removePhoto(index); }} className="absolute right-1 top-1 hidden rounded-full bg-navy px-1.5 text-xs text-white group-hover:block">×</button></div>)}</div> : null}</div></section>
    <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-lg shadow-slate-200/60 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-sky">Paso 4</p><h2 className="mt-2 text-2xl font-black text-navy">Ubicación del inmueble</h2><p className="mt-2 text-sm text-slate-500">Indica las coordenadas para mostrar tu propiedad en el mapa.</p></div><button type="button" onClick={useCurrentLocation} disabled={locating} className="rounded-lg border border-blue px-4 py-2.5 text-sm font-bold text-blue transition hover:bg-blue hover:text-white disabled:opacity-60">{locating ? "Obteniendo ubicación..." : "Usar mi ubicación actual"}</button></div><div className="mt-6 grid gap-5 md:grid-cols-2"><label className="space-y-2"><span className="text-sm font-bold text-navy">Latitud</span><input required type="number" step="any" value={values.latitude} onChange={(event) => updateValue("latitude", event.target.value)} placeholder="-0.967600" className="field-input" /></label><label className="space-y-2"><span className="text-sm font-bold text-navy">Longitud</span><input required type="number" step="any" value={values.longitude} onChange={(event) => updateValue("longitude", event.target.value)} placeholder="-80.712700" className="field-input" /></label></div><LocationPickerMap latitude={values.latitude} longitude={values.longitude} onChange={updateCoordinates} /></section>
    {error ? <p role="alert" className="rounded-lg bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</p> : null}{success ? <p role="status" className="rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm font-semibold text-green-700">¡Propiedad lista! La publicación se ha guardado de forma simulada.</p> : null}<div className="flex justify-end"><button type="submit" className="w-full rounded-xl bg-orange px-7 py-3.5 font-bold text-white shadow-lg shadow-orange/20 transition hover:-translate-y-0.5 hover:bg-[#d85c13] sm:w-auto">Publicar Propiedad <span className="ml-2">→</span></button></div>
  </form>;
}
