"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

type Props = { role: "ARRENDADOR" | "ARRENDATARIO" };
type Chat = { id: string; propertyId: string; senderId: string; recipientId: string; content: string; createdAt: string; property?: { title: string; landlordId: string }; senderName: string; recipientName: string };
type Request = { id: string; status: string; message?: string; createdAt: string; properties: { id: string; title: string; address: string; monthlyRent: number; landlordId: string }; users: { fullName: string; email: string; phone?: string; nationalId?: string } };
type Contract = { id: string; status: string; startDate: string; endDate: string; tenantSignedAt?: string; landlordSignedAt?: string; properties: { title: string; address: string }; users_contracts_tenantIdTousers: { fullName: string }; users_contracts_landlordIdTousers: { fullName: string } };

export function RentalWorkspace({ role }: Props) {
  const [chats, setChats] = useState<Chat[]>([]); const [currentUserId, setCurrentUserId] = useState(""); const [requests, setRequests] = useState<Request[]>([]); const [contracts, setContracts] = useState<Contract[]>([]); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  const load = async () => { try { const [chatRes, requestRes, contractRes] = await Promise.all([fetch("/api/chat"), fetch("/api/contract-requests"), fetch("/api/contracts")]); const [chatData, requestData, contractData] = await Promise.all([chatRes.json(), requestRes.json(), contractRes.json()]); if (!chatRes.ok) throw new Error(chatData.error); setChats(chatData.messages ?? []); setCurrentUserId(chatData.currentUserId ?? ""); setRequests(requestData.requests ?? []); setContracts(contractData.contracts ?? []); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo cargar el espacio de gestión"); } };
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 15000); return () => window.clearInterval(timer); }, []);
  const decide = async (id: string, decision: "APROBADO" | "RECHAZADO") => { setBusy(id); const response = await fetch(`/api/contract-requests/${id}/decision`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision }) }); const data = await response.json(); setBusy(null); if (!response.ok) return setError(data.error ?? "No se pudo procesar la solicitud"); await load(); };
  const sign = async (id: string) => { setBusy(id); const response = await fetch(`/api/contracts/${id}/sign`, { method: "POST" }); const data = await response.json(); setBusy(null); if (!response.ok) return setError(data.error ?? "No se pudo confirmar"); await load(); };
  const requestContract = async (propertyId: string) => { setBusy(propertyId); const response = await fetch("/api/contract-requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ propertyId, message: "Solicito preparar el contrato luego de nuestra conversación." }) }); const data = await response.json(); setBusy(null); if (!response.ok) return setError(data.error ?? "No se pudo enviar la solicitud"); await load(); };
  const sendReply = async (event: FormEvent<HTMLFormElement>, chat: Chat) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const content = String(form.get("content") ?? ""); const recipientId = chat.senderId === currentUserId ? chat.recipientId : chat.senderId; if (!content.trim() || !recipientId) return; setBusy(chat.id); const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ propertyId: chat.propertyId, recipientId, content }) }); const data = await response.json(); setBusy(null); if (!response.ok) return setError(data.error ?? "No se pudo enviar el mensaje"); formElement.reset(); await load(); };
  const conversations = Object.values(chats.reduce<Record<string, Chat[]>>((all, chat) => { (all[chat.propertyId] ??= []).push(chat); return all; }, {}));
  return <section className="space-y-8">
    {error ? <p className="rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p> : null}
    <div className="grid gap-4 sm:grid-cols-3"><Summary label="Conversaciones" value={String(conversations.length)} /><Summary label={role === "ARRENDADOR" ? "Solicitudes recibidas" : "Mis solicitudes"} value={String(requests.filter((item) => item.status === "PENDIENTE").length)} /><Summary label="Contratos" value={String(contracts.length)} /></div>
    <div className="grid gap-8 xl:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-black text-navy">Mensajes</h3><p className="mt-1 text-sm text-slate-500">Consultas directas sobre cada propiedad.</p><div className="mt-5 space-y-4">{conversations.length === 0 ? <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Todavía no hay conversaciones.</p> : conversations.map((thread) => { const last = thread.at(-1)!; return <article key={last.propertyId} className="rounded-xl border border-slate-200 p-4"><p className="font-bold text-navy">{last.property?.title ?? "Propiedad"}</p><p className="mt-2 text-sm text-slate-600"><b>{last.senderName}:</b> {last.content}</p>{role === "ARRENDADOR" ? <form onSubmit={(event) => void sendReply(event, last)} className="mt-3 flex gap-2"><input name="content" required placeholder="Responder consulta..." className="min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2 text-sm" /><button disabled={busy === last.id} className="rounded-lg bg-blue px-3 py-2 text-sm font-bold text-white">Enviar</button></form> : <button disabled={busy === last.propertyId} onClick={() => void requestContract(last.propertyId)} className="mt-3 rounded-lg bg-orange px-3 py-2 text-sm font-bold text-white">Solicitar contrato</button>}</article>; })}</div></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-black text-navy">Solicitudes de contrato</h3><p className="mt-1 text-sm text-slate-500">Aceptar prepara el contrato; aún no ocupa el inmueble.</p><div className="mt-5 space-y-4">{requests.length === 0 ? <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No hay solicitudes todavía.</p> : requests.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-navy">{item.properties.title}</p><p className="text-sm text-slate-500">{role === "ARRENDADOR" ? `Interesado: ${item.users.fullName}` : item.properties.address}</p></div><span className="rounded-full bg-sky/10 px-2 py-1 text-xs font-bold text-blue">{item.status}</span></div>{item.message ? <p className="mt-3 text-sm text-slate-600">“{item.message}”</p> : null}{role === "ARRENDADOR" && item.status === "PENDIENTE" ? <div className="mt-4 flex gap-2"><button disabled={busy === item.id} onClick={() => void decide(item.id, "APROBADO")} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-bold text-white">Aceptar y preparar</button><button disabled={busy === item.id} onClick={() => void decide(item.id, "RECHAZADO")} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-700">Rechazar</button></div> : null}</article>)}</div></div></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-black text-navy">Contratos y formalización</h3><p className="mt-1 text-sm text-slate-500">El inmueble pasa a ocupado únicamente después de las dos confirmaciones.</p><div className="mt-5 grid gap-4 lg:grid-cols-2">{contracts.length === 0 ? <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Aún no tienes contratos.</p> : contracts.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-4"><p className="font-bold text-navy">{item.properties.title}</p><p className="mt-1 text-sm text-slate-500">{new Date(item.startDate).toLocaleDateString("es-EC")} - {new Date(item.endDate).toLocaleDateString("es-EC")}</p><p className="mt-2 text-xs font-bold text-blue">{item.status === "PENDIENTE_FIRMA" ? `Pendiente: ${item.landlordSignedAt ? "arrendatario" : item.tenantSignedAt ? "arrendador" : "ambas partes"}` : item.status}</p><div className="mt-4 flex flex-wrap gap-2"><Link href={`/contratos/${item.id}`} className="rounded-lg border border-blue px-3 py-2 text-sm font-bold text-blue">Ver e imprimir PDF</Link>{item.status === "PENDIENTE_FIRMA" ? <button disabled={busy === item.id} onClick={() => void sign(item.id)} className="rounded-lg bg-orange px-3 py-2 text-sm font-bold text-white">Confirmar mis datos</button> : null}</div></article>)}</div></div>
  </section>;
}
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-navy p-5 text-white"><p className="text-sm font-semibold text-blue-100">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>; }
