"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

type Props = { role: "ARRENDADOR" | "ARRENDATARIO" };
type Chat = { id: string; propertyId: string; senderId: string; recipientId: string; content: string; createdAt: string; property?: { title: string; landlordId: string }; senderName: string; recipientName: string };
type Request = { id: string; status: string; message?: string; createdAt: string; properties: { id: string; title: string; address: string; monthlyRent: number; landlordId: string }; users: { fullName: string; email: string; phone?: string; nationalId?: string } };
type Contract = { id: string; status: string; startDate: string; endDate: string; tenantSignedAt?: string; landlordSignedAt?: string; properties: { title: string; address: string }; users_contracts_tenantIdTousers: { fullName: string }; users_contracts_landlordIdTousers: { fullName: string } };
type Report = { id: string; description: string; incidentDate: string; status: string; properties: { title: string; address: string }; users_incident_reports_tenantIdTousers: { fullName: string; email: string } };
const todayIsoDate = () => new Date().toISOString().slice(0, 10);
const REPORT_STATUS_LABEL: Record<string, string> = { PENDIENTE: "Pendiente", EN_PROCESO: "En proceso", RESUELTO: "Resuelto" };
const REPORT_STATUS_BADGE: Record<string, string> = { PENDIENTE: "bg-amber-100 text-amber-800", EN_PROCESO: "bg-sky/10 text-blue", RESUELTO: "bg-emerald-100 text-emerald-700" };

export function RentalWorkspace({ role }: Props) {
  const [chats, setChats] = useState<Chat[]>([]); const [currentUserId, setCurrentUserId] = useState(""); const [requests, setRequests] = useState<Request[]>([]); const [contracts, setContracts] = useState<Contract[]>([]); const [reports, setReports] = useState<Report[]>([]); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  const [incidentContract, setIncidentContract] = useState<Contract | null>(null); const [incidentDescription, setIncidentDescription] = useState(""); const [incidentDate, setIncidentDate] = useState(todayIsoDate()); const [incidentSubmitting, setIncidentSubmitting] = useState(false); const [incidentError, setIncidentError] = useState<string | null>(null); const [incidentSuccess, setIncidentSuccess] = useState(false);
  const load = async () => { try { const [chatRes, requestRes, contractRes, reportRes] = await Promise.all([fetch("/api/chat"), fetch("/api/contract-requests"), fetch("/api/contracts"), fetch("/api/incident-reports")]); const [chatData, requestData, contractData, reportData] = await Promise.all([chatRes.json(), requestRes.json(), contractRes.json(), reportRes.json()]); if (!chatRes.ok) throw new Error(chatData.error); setChats(chatData.messages ?? []); setCurrentUserId(chatData.currentUserId ?? ""); setRequests(requestData.requests ?? []); setContracts(contractData.contracts ?? []); setReports(reportData.reports ?? []); } catch (e) { setError(e instanceof Error ? e.message : "No se pudo cargar el espacio de gestión"); } };
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 15000); return () => window.clearInterval(timer); }, []);
  useEffect(() => { function closeWithEscape(event: KeyboardEvent) { if (event.key === "Escape") setIncidentContract(null); } if (!incidentContract) return; document.addEventListener("keydown", closeWithEscape); document.body.style.overflow = "hidden"; return () => { document.removeEventListener("keydown", closeWithEscape); document.body.style.overflow = ""; }; }, [incidentContract]);
  const decide = async (id: string, decision: "APROBADO" | "RECHAZADO") => { setBusy(id); const response = await fetch(`/api/contract-requests/${id}/decision`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision }) }); const data = await response.json(); setBusy(null); if (!response.ok) return setError(data.error ?? "No se pudo procesar la solicitud"); await load(); };
  const sign = async (id: string) => { setBusy(id); const response = await fetch(`/api/contracts/${id}/sign`, { method: "POST" }); const data = await response.json(); setBusy(null); if (!response.ok) return setError(data.error ?? "No se pudo confirmar"); await load(); };
  const requestContract = async (propertyId: string) => { setBusy(propertyId); const response = await fetch("/api/contract-requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ propertyId, message: "Solicito preparar el contrato luego de nuestra conversación." }) }); const data = await response.json(); setBusy(null); if (!response.ok) return setError(data.error ?? "No se pudo enviar la solicitud"); await load(); };
  const updateReportStatus = async (id: string, status: string) => { setBusy(id); const response = await fetch(`/api/incident-reports/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const data = await response.json(); setBusy(null); if (!response.ok) return setError(data.error ?? "No se pudo actualizar el estado del reporte"); await load(); };
  const sendReply = async (event: FormEvent<HTMLFormElement>, chat: Chat) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const content = String(form.get("content") ?? ""); const recipientId = chat.senderId === currentUserId ? chat.recipientId : chat.senderId; if (!content.trim() || !recipientId) return; setBusy(chat.id); const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ propertyId: chat.propertyId, recipientId, content }) }); const data = await response.json(); setBusy(null); if (!response.ok) return setError(data.error ?? "No se pudo enviar el mensaje"); formElement.reset(); await load(); };
  const conversations = Object.values(chats.reduce<Record<string, Chat[]>>((all, chat) => { (all[chat.propertyId] ??= []).push(chat); return all; }, {}));
  const openIncidentForm = (contract: Contract) => { setIncidentContract(contract); setIncidentDescription(""); setIncidentDate(todayIsoDate()); setIncidentError(null); setIncidentSuccess(false); };
  const submitIncident = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!incidentContract) return;
    setIncidentSubmitting(true); setIncidentError(null);
    try {
      const response = await fetch("/api/incident-reports", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ contractId: incidentContract.id, description: incidentDescription, incidentDate: new Date(incidentDate).toISOString() }) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error ?? "No se pudo enviar el reporte");
      setIncidentSuccess(true);
    } catch (submitError) {
      setIncidentError(submitError instanceof Error ? submitError.message : "No se pudo enviar el reporte");
    } finally {
      setIncidentSubmitting(false);
    }
  };
  return <section className="space-y-8">
    {error ? <p className="rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p> : null}
    <div className="grid gap-4 sm:grid-cols-3"><Summary label="Conversaciones" value={String(conversations.length)} /><Summary label={role === "ARRENDADOR" ? "Solicitudes recibidas" : "Mis solicitudes"} value={String(requests.filter((item) => item.status === "PENDIENTE").length)} /><Summary label="Contratos" value={String(contracts.length)} /></div>
    <div className="grid grid-cols-1 items-start gap-6 lg:grid-cols-2">
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-black text-navy">Mensajes</h3><p className="mt-1 text-sm text-slate-500">Consultas directas sobre cada propiedad.</p><div className="mt-5 h-[280px] space-y-4 overflow-y-auto pr-2">{conversations.length === 0 ? <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Todavía no hay conversaciones.</p> : conversations.map((thread) => { const last = thread.at(-1)!; return <article key={last.propertyId} className="rounded-xl border border-slate-200 p-4"><p className="font-bold text-navy">{last.property?.title ?? "Propiedad"}</p><p className="mt-2 text-sm text-slate-600"><b>{last.senderName}:</b> {last.content}</p>{role === "ARRENDADOR" ? <form onSubmit={(event) => void sendReply(event, last)} className="mt-3 flex gap-2"><input name="content" required placeholder="Responder consulta..." className="min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2 text-sm" /><button disabled={busy === last.id} className="rounded-lg bg-blue px-3 py-2 text-sm font-bold text-white">Enviar</button></form> : <button disabled={busy === last.propertyId} onClick={() => void requestContract(last.propertyId)} className="mt-3 rounded-lg bg-orange px-3 py-2 text-sm font-bold text-white">Solicitar contrato</button>}</article>; })}</div></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-black text-navy">Solicitudes de contrato</h3><p className="mt-1 text-sm text-slate-500">Aceptar prepara el contrato; aún no ocupa el inmueble.</p><div className="mt-5 h-[280px] space-y-4 overflow-y-auto pr-2">{requests.length === 0 ? <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No hay solicitudes todavía.</p> : requests.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-navy">{item.properties.title}</p><p className="text-sm text-slate-500">{role === "ARRENDADOR" ? `Interesado: ${item.users.fullName}` : item.properties.address}</p></div><span className="rounded-full bg-sky/10 px-2 py-1 text-xs font-bold text-blue">{item.status}</span></div>{item.message ? <p className="mt-3 text-sm text-slate-600">“{item.message}”</p> : null}{role === "ARRENDADOR" && item.status === "PENDIENTE" ? <div className="mt-4 flex gap-2"><button disabled={busy === item.id} onClick={() => void decide(item.id, "APROBADO")} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-bold text-white">Aceptar y preparar</button><button disabled={busy === item.id} onClick={() => void decide(item.id, "RECHAZADO")} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-700">Rechazar</button></div> : null}</article>)}</div></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-black text-navy">Quejas y mantenimiento</h3><p className="mt-1 text-sm text-slate-500">{role === "ARRENDADOR" ? "Incidencias reportadas por tus inquilinos sobre propiedades con contrato activo." : "Estado de las incidencias que has reportado en tus contratos activos."}</p><div className="mt-5 h-[280px] space-y-4 overflow-y-auto pr-2">{reports.length === 0 ? <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No hay reportes de incidencias todavía.</p> : reports.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-navy">{item.properties.title}</p>{role === "ARRENDADOR" ? <p className="text-sm text-slate-500">Inquilino: {item.users_incident_reports_tenantIdTousers.fullName}</p> : null}<p className="mt-1 text-xs text-slate-500">Reportado el {new Date(item.incidentDate).toLocaleDateString("es-EC")}</p></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${REPORT_STATUS_BADGE[item.status] ?? "bg-slate-100 text-slate-600"}`}>{REPORT_STATUS_LABEL[item.status] ?? item.status}</span></div><p className="mt-3 text-sm text-slate-600">“{item.description}”</p>{role === "ARRENDADOR" ? <label className="mt-4 block max-w-xs space-y-1"><span className="text-xs font-bold uppercase tracking-wide text-navy">Cambiar estado</span><select disabled={busy === item.id} value={item.status} onChange={(event) => void updateReportStatus(item.id, event.target.value)} className="field-input px-3 py-2 text-sm"><option value="PENDIENTE">Pendiente</option><option value="EN_PROCESO">En proceso</option><option value="RESUELTO">Resuelto</option></select></label> : null}</article>)}</div></div>
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-xl font-black text-navy">Contratos y formalización</h3><p className="mt-1 text-sm text-slate-500">El inmueble pasa a ocupado únicamente después de las dos confirmaciones.</p><div className="mt-5 grid h-[280px] gap-4 overflow-y-auto pr-2">{contracts.length === 0 ? <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Aún no tienes contratos.</p> : contracts.map((item) => <article key={item.id} className="rounded-xl border border-slate-200 p-4"><p className="font-bold text-navy">{item.properties.title}</p><p className="mt-1 text-sm text-slate-500">{new Date(item.startDate).toLocaleDateString("es-EC")} - {new Date(item.endDate).toLocaleDateString("es-EC")}</p><p className="mt-2 text-xs font-bold text-blue">{item.status === "PENDIENTE_FIRMA" ? `Pendiente: ${item.landlordSignedAt ? "arrendatario" : item.tenantSignedAt ? "arrendador" : "ambas partes"}` : item.status}</p><div className="mt-4 flex flex-wrap gap-2"><Link href={`/contratos/${item.id}`} className="rounded-lg border border-blue px-3 py-2 text-sm font-bold text-blue">Ver e imprimir PDF</Link>{item.status === "PENDIENTE_FIRMA" ? <button disabled={busy === item.id} onClick={() => void sign(item.id)} className="rounded-lg bg-orange px-3 py-2 text-sm font-bold text-white">Confirmar mis datos</button> : null}{role === "ARRENDATARIO" && item.status === "ACTIVO" ? <button onClick={() => openIncidentForm(item)} className="rounded-lg border border-red-200 px-3 py-2 text-sm font-bold text-red-700 transition hover:bg-red-50">Reportar problema</button> : null}</div></article>)}</div></div>
    </div>
    {incidentContract ? <div role="presentation" className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4 backdrop-blur-sm" onMouseDown={(event) => { if (event.target === event.currentTarget) setIncidentContract(null); }}><div role="dialog" aria-modal="true" aria-labelledby="incident-modal-title" className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-orange">Nueva incidencia</p><h2 id="incident-modal-title" className="mt-2 text-2xl font-black text-navy">Reportar problema</h2><p className="mt-2 text-sm text-slate-500">Sobre: {incidentContract.properties.title}</p></div><button type="button" aria-label="Cerrar reporte" onClick={() => setIncidentContract(null)} className="grid h-9 w-9 place-items-center rounded-full bg-slate-100 text-xl font-bold text-navy">×</button></div>{incidentSuccess ? <div role="status" className="mt-6 rounded-xl border border-green-200 bg-green-50 p-4 text-sm font-semibold text-green-700">Reporte enviado. El arrendador podrá revisarlo y darle seguimiento desde su panel.</div> : <form onSubmit={submitIncident} className="mt-6 space-y-4"><label className="block space-y-2"><span className="text-sm font-bold text-navy">Descripción del problema</span><textarea required minLength={10} maxLength={2000} rows={4} value={incidentDescription} onChange={(event) => setIncidentDescription(event.target.value)} placeholder="Describe el daño o la avería que encontraste en la propiedad..." className="field-input resize-y" /></label><label className="block space-y-2"><span className="text-sm font-bold text-navy">Fecha en la que ocurrió</span><input required type="date" max={todayIsoDate()} value={incidentDate} onChange={(event) => setIncidentDate(event.target.value)} className="field-input" /></label>{incidentError ? <p role="alert" className="rounded-lg bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{incidentError}</p> : null}<button type="submit" disabled={incidentSubmitting} className="w-full rounded-xl bg-orange px-6 py-3.5 font-bold text-white transition hover:bg-[#d85c13] disabled:cursor-wait disabled:opacity-60">{incidentSubmitting ? "Enviando..." : "Enviar reporte"}</button></form>}</div></div> : null}
  </section>;
}
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-navy p-5 text-white"><p className="text-sm font-semibold text-blue-100">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>; }
