"use client";

import Link from "next/link";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { ContractRenewalPanel } from "@/components/contract-renewal-panel";
import { ContractTerminationButton } from "@/components/contract-termination-button";
import { Alert, Button, Dialog, EmptyState, StatCard, StatusBadge } from "@/components/ui";

export type WorkspaceModule = "summary" | "messages" | "requests" | "contracts" | "incidents" | "renewals";
type Props = { role: "ARRENDADOR" | "ARRENDATARIO"; module?: WorkspaceModule };
type Chat = { id: string; propertyId: string; senderId: string; recipientId: string; content: string; createdAt: string; property?: { title: string; landlordId: string }; senderName: string; recipientName: string };
type Request = { id: string; status: string; message?: string; createdAt: string; properties: { id: string; title: string; address: string; monthlyRent: number; landlordId: string }; users: { fullName: string; email: string; phone?: string; nationalId?: string } };
type Contract = { id: string; status: string; startDate: string; endDate: string; tenantSignedAt?: string; landlordSignedAt?: string; properties: { title: string; address: string }; users_contracts_tenantIdTousers: { fullName: string }; users_contracts_landlordIdTousers: { fullName: string } };
type Report = { id: string; description: string; incidentDate: string; status: string; properties: { title: string; address: string }; users_incident_reports_tenantIdTousers: { fullName: string; email: string } };
const todayIsoDate = () => new Date().toISOString().slice(0, 10);

const moduleContent: Record<WorkspaceModule, { title: string; description: string }> = {
  summary: { title: "Resumen de actividad", description: "Tus acciones importantes en un solo vistazo." },
  messages: { title: "Mensajes", description: "Conversaciones relacionadas con tus propiedades y solicitudes." },
  requests: { title: "Solicitudes", description: "Solicitudes de contrato y sus decisiones." },
  contracts: { title: "Contratos", description: "Consulta firmas, documentos y estado del ciclo contractual." },
  incidents: { title: "Incidencias", description: "Seguimiento de reportes de mantenimiento." },
  renewals: { title: "Renovaciones", description: "Gestiona solicitudes dentro de la ventana contractual permitida." },
};

export function RentalWorkspace({ role, module = "summary" }: Props) {
  const [chats, setChats] = useState<Chat[]>([]); const [currentUserId, setCurrentUserId] = useState(""); const [requests, setRequests] = useState<Request[]>([]); const [contracts, setContracts] = useState<Contract[]>([]); const [reports, setReports] = useState<Report[]>([]); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null);
  const [incidentContract, setIncidentContract] = useState<Contract | null>(null); const [incidentDescription, setIncidentDescription] = useState(""); const [incidentDate, setIncidentDate] = useState(todayIsoDate()); const [incidentSubmitting, setIncidentSubmitting] = useState(false); const [incidentError, setIncidentError] = useState<string | null>(null); const [incidentSuccess, setIncidentSuccess] = useState(false);
  const basePath = role === "ARRENDADOR" ? "/panel/arrendador" : "/panel/arrendatario";
  const copy = moduleContent[module];

  const load = async () => { try { const [chatRes, requestRes, contractRes, reportRes] = await Promise.all([fetch("/api/chat"), fetch("/api/contract-requests"), fetch("/api/contracts"), fetch("/api/incident-reports")]); const [chatData, requestData, contractData, reportData] = await Promise.all([chatRes.json(), requestRes.json(), contractRes.json(), reportRes.json()]); if (!chatRes.ok) throw new Error(chatData.error); setChats(chatData.messages ?? []); setCurrentUserId(chatData.currentUserId ?? ""); setRequests(requestData.requests ?? []); setContracts(contractData.contracts ?? []); setReports(reportData.reports ?? []); } catch (cause) { setError(cause instanceof Error ? cause.message : "No se pudo cargar este módulo"); } };
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 15_000); return () => window.clearInterval(timer); }, []);
  const decide = async (id: string, decision: "APROBADO" | "RECHAZADO") => { setBusy(id); const response = await fetch(`/api/contract-requests/${id}/decision`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision }) }); const data = await response.json(); setBusy(null); if (!response.ok) return setError(data.error ?? "No se pudo procesar la solicitud"); await load(); };
  const sign = async (id: string) => { setBusy(id); const response = await fetch(`/api/contracts/${id}/sign`, { method: "POST" }); const data = await response.json(); setBusy(null); if (!response.ok) return setError(data.error ?? "No se pudo confirmar la firma"); await load(); };
  const requestContract = async (propertyId: string) => { setBusy(propertyId); const response = await fetch("/api/contract-requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ propertyId, message: "Solicito preparar el contrato luego de nuestra conversación." }) }); const data = await response.json(); setBusy(null); if (!response.ok) return setError(data.error ?? "No se pudo enviar la solicitud"); await load(); };
  const updateReportStatus = async (id: string, status: string) => { setBusy(id); const response = await fetch(`/api/incident-reports/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); const data = await response.json(); setBusy(null); if (!response.ok) return setError(data.error ?? "No se pudo actualizar el reporte"); await load(); };
  const sendReply = async (event: FormEvent<HTMLFormElement>, chat: Chat) => { event.preventDefault(); const form = new FormData(event.currentTarget); const content = String(form.get("content") ?? ""); const recipientId = chat.senderId === currentUserId ? chat.recipientId : chat.senderId; if (!content.trim() || !recipientId) return; setBusy(chat.id); const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ propertyId: chat.propertyId, recipientId, content }) }); const data = await response.json(); setBusy(null); if (!response.ok) return setError(data.error ?? "No se pudo enviar el mensaje"); event.currentTarget.reset(); await load(); };
  const conversations = useMemo(() => Object.values(chats.reduce<Record<string, Chat[]>>((all, chat) => { (all[chat.propertyId] ??= []).push(chat); return all; }, {})), [chats]);
  const activeContracts = contracts.filter((contract) => contract.status === "ACTIVO" || contract.status === "EN_RENOVACION");
  const openIncidentForm = (contract: Contract) => { setIncidentContract(contract); setIncidentDescription(""); setIncidentDate(todayIsoDate()); setIncidentError(null); setIncidentSuccess(false); };
  const submitIncident = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!incidentContract) return; setIncidentSubmitting(true); setIncidentError(null); try { const response = await fetch("/api/incident-reports", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ contractId: incidentContract.id, description: incidentDescription, incidentDate: new Date(incidentDate).toISOString() }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "No se pudo enviar el reporte"); setIncidentSuccess(true); await load(); } catch (cause) { setIncidentError(cause instanceof Error ? cause.message : "No se pudo enviar el reporte"); } finally { setIncidentSubmitting(false); } };

  return <section className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-sky">{role === "ARRENDADOR" ? "Gestión de arriendos" : "Mi espacio"}</p><h2 className="mt-2 text-2xl font-black text-navy sm:text-3xl">{copy.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.description}</p></div>{module === "incidents" && role === "ARRENDATARIO" && activeContracts.length > 0 ? <Button onClick={() => openIncidentForm(activeContracts[0])}>+ Reportar incidencia</Button> : null}</div>{error ? <Alert tone="danger" title="No se pudo actualizar este módulo">{error}</Alert> : null}
    {module === "summary" ? <SummaryView basePath={basePath} role={role} conversations={conversations.length} pendingRequests={requests.filter((item) => item.status === "PENDIENTE").length} activeContracts={activeContracts.length} openReports={reports.filter((item) => item.status !== "RESUELTO").length} hasActiveContract={activeContracts.length > 0} /> : null}
    {module === "messages" ? <div className="space-y-3">{conversations.length === 0 ? <EmptyState title="Todavía no hay conversaciones" description="Explora propiedades y contacta al arrendador para iniciar una conversación." action={<Link className="font-bold text-blue hover:underline" href={`${basePath}/explorar`}>Explorar propiedades</Link>} /> : conversations.map((thread) => { const last = thread.at(-1)!; return <article key={last.propertyId} className="app-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-black text-navy">{last.property?.title ?? "Propiedad"}</p><p className="mt-1 text-sm text-muted-foreground"><b>{last.senderName}:</b> {last.content}</p></div><span className="text-xs text-muted-foreground">{new Date(last.createdAt).toLocaleDateString("es-EC")}</span></div>{role === "ARRENDADOR" ? <form onSubmit={(event) => void sendReply(event, last)} className="mt-4 flex flex-col gap-2 sm:flex-row"><label className="sr-only" htmlFor={`reply-${last.id}`}>Responder</label><input id={`reply-${last.id}`} name="content" required placeholder="Responder consulta…" className="field-input min-w-0 flex-1 px-3 py-2" /><Button loading={busy === last.id} type="submit">Enviar</Button></form> : <Button className="mt-4" loading={busy === last.propertyId} variant="accent" onClick={() => void requestContract(last.propertyId)}>Solicitar contrato</Button>}</article>; })}</div> : null}
    {module === "requests" ? <div className="space-y-3">{requests.length === 0 ? <EmptyState title="No tienes solicitudes todavía" description="Explora propiedades disponibles para comenzar una solicitud." action={<Link className="font-bold text-blue hover:underline" href={`${basePath}/explorar`}>Explorar propiedades</Link>} /> : requests.map((item) => <article key={item.id} className="app-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-black text-navy">{item.properties.title}</p><p className="mt-1 text-sm text-muted-foreground">{role === "ARRENDADOR" ? `Interesado: ${item.users.fullName}` : item.properties.address}</p></div><StatusBadge status={item.status} /></div>{item.message ? <p className="mt-3 text-sm text-slate-600">“{item.message}”</p> : null}{role === "ARRENDADOR" && item.status === "PENDIENTE" ? <div className="mt-4 flex flex-wrap gap-2"><Button loading={busy === item.id} onClick={() => void decide(item.id, "APROBADO")}>Aceptar y preparar</Button><Button loading={busy === item.id} variant="danger" onClick={() => void decide(item.id, "RECHAZADO")}>Rechazar</Button></div> : null}</article>)}</div> : null}
    {module === "incidents" ? <div className="space-y-3">{reports.length === 0 ? <EmptyState title="No hay incidencias registradas" description={role === "ARRENDATARIO" ? "Si detectas un problema en una propiedad con contrato activo, repórtalo desde aquí." : "Cuando un inquilino reporte un problema, aparecerá en este módulo."} action={role === "ARRENDATARIO" && activeContracts.length > 0 ? <Button onClick={() => openIncidentForm(activeContracts[0])}>+ Reportar incidencia</Button> : undefined} /> : reports.map((item) => <article key={item.id} className="app-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-black text-navy">{item.properties.title}</p>{role === "ARRENDADOR" ? <p className="mt-1 text-sm text-muted-foreground">Inquilino: {item.users_incident_reports_tenantIdTousers.fullName}</p> : null}<p className="mt-1 text-xs text-muted-foreground">Reportado el {new Date(item.incidentDate).toLocaleDateString("es-EC")}</p></div><StatusBadge status={item.status} /></div><p className="mt-3 text-sm leading-6 text-slate-600">“{item.description}”</p>{role === "ARRENDADOR" ? <label className="mt-4 block max-w-xs"><span className="text-xs font-extrabold uppercase tracking-wide text-navy">Cambiar estado</span><select disabled={busy === item.id} value={item.status} onChange={(event) => void updateReportStatus(item.id, event.target.value)} className="field-input mt-2 px-3 py-2 text-sm"><option value="PENDIENTE">Pendiente</option><option value="EN_PROCESO">En proceso</option><option value="RESUELTO">Resuelto</option></select></label> : null}</article>)}</div> : null}
    {module === "contracts" ? <div className="space-y-3">{contracts.length === 0 ? <EmptyState title="Aún no tienes contratos" description="Las formalizaciones aparecerán aquí cuando una solicitud avance." action={<Link className="font-bold text-blue hover:underline" href={`${basePath}/solicitudes`}>Ver solicitudes</Link>} /> : contracts.map((item) => <article key={item.id} className="app-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-black text-navy">{item.properties.title}</p><p className="mt-1 text-sm text-muted-foreground">{new Date(item.startDate).toLocaleDateString("es-EC")} – {new Date(item.endDate).toLocaleDateString("es-EC")}</p><p className="mt-1 text-xs text-muted-foreground">{role === "ARRENDADOR" ? item.users_contracts_tenantIdTousers.fullName : item.users_contracts_landlordIdTousers.fullName}</p></div><StatusBadge status={item.status} /></div><div className="mt-4 flex flex-wrap gap-2"><Link href={`/contratos/${item.id}`} className="inline-flex min-h-10 items-center justify-center rounded-md border border-border bg-surface px-4 py-2.5 text-sm font-bold text-blue transition hover:border-sky hover:bg-sky/5">Ver e imprimir PDF</Link>{item.status === "PENDIENTE_FIRMA" ? <Button loading={busy === item.id} variant="accent" onClick={() => void sign(item.id)}>Confirmar mis datos</Button> : null}{role === "ARRENDATARIO" && item.status === "ACTIVO" ? <Button variant="secondary" onClick={() => openIncidentForm(item)}>Reportar incidencia</Button> : null}</div></article>)}</div> : null}
    {module === "renewals" ? <ContractRenewalPanel role={role} contracts={contracts} onChanged={load} /> : null}
    {module === "contracts" && activeContracts.length > 0 ? <section className="app-panel border-red-100 p-5"><h3 className="font-black text-navy">Finalizar contratos</h3><p className="mt-1 text-sm text-muted-foreground">El historial se conservará después de la finalización.</p><div className="mt-4 space-y-3">{activeContracts.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-surface-subtle p-4"><div><p className="font-bold text-navy">{item.properties.title}</p><StatusBadge status={item.status} className="mt-1" /></div><ContractTerminationButton contractId={item.id} onCompleted={load} /></div>)}</div></section> : null}
    <Dialog open={incidentContract !== null} onClose={() => !incidentSubmitting && setIncidentContract(null)} title="Reportar incidencia" description={incidentContract ? `Sobre: ${incidentContract.properties.title}` : undefined}>{incidentSuccess ? <Alert tone="success" title="Reporte enviado">El arrendador podrá revisarlo y darle seguimiento desde su panel.</Alert> : <form onSubmit={submitIncident} className="space-y-4"><label className="block"><span className="text-sm font-bold text-navy">Descripción del problema</span><textarea required minLength={10} maxLength={2000} rows={4} value={incidentDescription} onChange={(event) => setIncidentDescription(event.target.value)} placeholder="Describe el daño o la avería encontrada…" className="field-input mt-2 resize-y" /></label><label className="block max-w-xs"><span className="text-sm font-bold text-navy">Fecha del incidente</span><input required type="date" value={incidentDate} onChange={(event) => setIncidentDate(event.target.value)} className="field-input mt-2" /></label>{incidentError ? <Alert tone="danger">{incidentError}</Alert> : null}<div className="flex flex-wrap justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setIncidentContract(null)}>Cancelar</Button><Button type="submit" loading={incidentSubmitting}>Enviar reporte</Button></div></form>}</Dialog>
  </section>;
}

function SummaryView({ basePath, role, conversations, pendingRequests, activeContracts, openReports, hasActiveContract }: { basePath: string; role: Props["role"]; conversations: number; pendingRequests: number; activeContracts: number; openReports: number; hasActiveContract: boolean }) {
  const cards = [{ label: "Solicitudes pendientes", value: pendingRequests, href: "solicitudes", tone: "orange" as const }, { label: "Contratos vigentes", value: activeContracts, href: "contratos", tone: "sky" as const }, { label: "Incidencias abiertas", value: openReports, href: "incidencias", tone: "blue" as const }, { label: "Conversaciones", value: conversations, href: "mensajes", tone: "violet" as const }];
  return <><section className="rounded-xl border border-border bg-surface px-4 py-3 sm:px-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black text-navy">Acciones rápidas</h3><p className="mt-0.5 text-sm text-muted-foreground">Accede a las tareas más frecuentes.</p></div><div className="flex flex-wrap gap-2">{role === "ARRENDATARIO" ? <><Link className="rounded-md bg-blue px-4 py-2.5 text-sm font-bold text-white" href={`${basePath}/explorar`}>Explorar propiedades</Link>{hasActiveContract ? <Link className="rounded-md border border-border px-4 py-2.5 text-sm font-bold text-blue" href={`${basePath}/incidencias`}>Reportar incidencia</Link> : <span className="inline-flex min-h-10 items-center rounded-md border border-border bg-surface-subtle px-4 py-2.5 text-sm font-bold text-muted-foreground" title="Disponible cuando tengas un contrato activo">Reportar incidencia</span>}<Link className="rounded-md border border-border px-4 py-2.5 text-sm font-bold text-blue" href={`${basePath}/documentos`}>Subir documentos</Link>{!hasActiveContract ? <Link className="rounded-md px-2 py-2.5 text-sm font-bold text-blue underline" href={`${basePath}/contratos`}>Ver contratos</Link> : null}</> : <><Link className="rounded-md bg-blue px-4 py-2.5 text-sm font-bold text-white" href={`${basePath}/propiedades`}>+ Nueva propiedad</Link><Link className="rounded-md border border-border px-4 py-2.5 text-sm font-bold text-blue" href={`${basePath}/propiedades`}>Gestionar propiedades</Link><Link className="rounded-md border border-border px-4 py-2.5 text-sm font-bold text-blue" href={`${basePath}/solicitudes`}>Revisar solicitudes</Link><Link className="rounded-md border border-border px-4 py-2.5 text-sm font-bold text-blue" href={`${basePath}/contratos`}>Ver contratos</Link></>}</div></div></section><section><h3 className="mb-3 font-black text-navy">Resumen de actividad</h3><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card) => <Link key={card.label} href={`${basePath}/${card.href}`} className="rounded-2xl focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-sky/25"><StatCard label={card.label} value={card.value} detail="Ver módulo" tone={card.tone} /></Link>)}</div></section></>;
}
